src/Entity/Comment.php
<?php

namespace App\Entity;

use App\Repository\CommentRepository;
use Doctrine\ORM\Mapping as ORM;

#[ORM\Entity(repositoryClass: CommentRepository::class)]
class Comment
{
    #[ORM\Id]
    #[ORM\GeneratedValue]
    #[ORM\Column]
    private ?int $id = null;

    #[ORM\Column(length: 255)]
    private ?string $content = null;

    #[ORM\Column]
    private ?\DateTimeImmutable $create_at = null;

    #[ORM\ManyToOne(inversedBy: 'comments')]
    #[ORM\JoinColumn(nullable: false)]
    private ?User $user = null;

    #[ORM\ManyToOne(inversedBy: 'comments')]
    #[ORM\JoinColumn(nullable: false)]
    private ?Photo $photo = null;

    public function getId(): ?int
    {
        return $this->id;
    }

    public function getContent(): ?string
    {
        return $this->content;
    }

    public function setContent(string $content): self
    {
        $this->content = $content;

        return $this;
    }

    public function getCreateAt(): ?\DateTimeImmutable
    {
        return $this->create_at;
    }

    public function setCreateAt(\DateTimeImmutable $create_at): self
    {
        $this->create_at = $create_at;

        return $this;
    }

    public function getUser(): ?User
    {
        return $this->user;
    }

    public function setUser(?User $user): self
    {
        $this->user = $user;

        return $this;
    }

    public function getPhoto(): ?Photo
    {
        return $this->photo;
    }

    public function setPhoto(?Photo $photo): self
    {
        $this->photo = $photo;

        return $this;
    }
}

src/Entity/Photo.php
<?php

namespace App\Entity;

use App\Repository\PhotoRepository;
use doctrine\Common\Collections\ArrayCollection;
use doctrine\Common\Collections\Collection;
use Doctrine\ORM\Mapping as ORM;
use Symfony\Component\HttpFoundation\File\File;
use Vich\UploaderBundle\Mapping\Annotation as Vich;

#[ORM\Entity(repositoryClass: PhotoRepository::class)]
#[Vich\Uploadable]
class Photo
{
    #[ORM\Id]
    #[ORM\GeneratedValue]
    #[ORM\Column]
    private ?int $id = null;

    #[ORM\Column(length: 255)]
    private ?string $title = null;

    #[ORM\Column(length: 255)]
    private ?string $imageName = null;

    #[Vich\UploadableField(mapping: 'uploaded_photos', fileNameProperty: 'imageName', size: 'imageSize')]
    private ?File $imageFile = null;

    #[ORM\Column(type: 'integer')]
     private ?int $imageSize = null; 

    #[ORM\Column]
    private ?\DateTimeImmutable $post_at = null;

    #[ORM\ManyToOne(inversedBy: 'photos')]
    #[ORM\JoinColumn(nullable: false)]
    private ?User $user = null;

    #[ORM\OneToMany(mappedBy: 'photo', targetEntity: Comment::class)]
    private \Doctrine\Common\Collections\Collection $comments;

    public function __construct()
    {
        $this->comments = new \Doctrine\Common\Collections\ArrayCollection();
    }

    public function getId(): ?int
    {
        return $this->id;
    }

    public function getTitle(): ?string
    {
        return $this->title;
    }

    public function setTitle(string $title): self
    {
        $this->title = $title;

        return $this;
    }

    public function getPostAt(): string
    {
        return date_format($this->post_at, 'Y-m-d H:i');
    } 

    public function setPostAt(\DateTimeImmutable $post_at): self
    {
        $this->post_at = $post_at;

        return $this;
    }

    public function getUser(): ?User
    {
        return $this->user;
    }

    public function setUser(?User $user): self
    {
        $this->user = $user;

        return $this;
    }

    /**
     * Get the value of imageFile
     */ 
    public function getImageFile()
    {
        return $this->imageFile;
    }

    /**
     * Set the value of imageFile
     *
     * @return  self
     */ 
    public function setImageFile(?File $imageFile= null): void
    {
        $this->imageFile = $imageFile;

        if(null !==$imageFile){
            $this->post_at = new \DateTimeImmutable();
        }

    }

     /**
      * Get the value of imageSize
      */ 
     public function getImageSize()
     {
          return $this->imageSize;
     }

     /**
      * Set the value of imageSize
      *
      * @return  self
      */ 
     public function setImageSize($imageSize)
     {
          $this->imageSize = $imageSize;

          return $this;
     }

    /**
     * Get the value of imageName
     */ 
    public function getImageName()
    {
        return $this->imageName;
    }

    /**
     * Set the value of imageName
     *
     * @return  self
     */ 
    public function setImageName($imageName)
    {
        $this->imageName = $imageName;

        return $this;
    }

    /**
     * @return \Doctrine\Common\Collections\Collection<int, Comment>
     */
    public function getComments(): \Doctrine\Common\Collections\Collection
    {
        return $this->comments;
    }

    public function addComment(Comment $comment): self
    {
        if (!$this->comments->contains($comment)) {
            $this->comments->add($comment);
            $comment->setPhoto($this);
        }

        return $this;
    }

    public function removeComment(Comment $comment): self
    {
        if ($this->comments->removeElement($comment)) {
            // set the owning side to null (unless already changed)
            if ($comment->getPhoto() === $this) {
                $comment->setPhoto(null);
            }
        }

        return $this;
    }
}

src/Form/photo/NewPhotoType.php
<?php

namespace App\Form;

use App\Entity\Photo;
use Symfony\Component\Form\AbstractType;
use Symfony\Component\Form\Extension\Core\Type\TextType as TypeTextType;
use Symfony\Component\Form\FormBuilderInterface;
use Symfony\Component\OptionsResolver\OptionsResolver;
use Vich\UploaderBundle\Form\Type\VichFileType;

class NewPhotoType extends AbstractType
{
    public function buildForm(FormBuilderInterface $builder, array $options): void
    {
        $builder
            ->add('title', TypeTextType::class, ['label' => 'Nom de la photo'])
            ->add('imageFile', VichFileType::class, ['label' => 'Votre photo']);
        
    }

    public function configureOptions(OptionsResolver $resolver): void
    {
        $resolver->setDefaults([
            'data_class' => Photo::class,
        ]);
    }
}

src/Controller/PhotoController.php
<?php

namespace App\Controller;

use App\Entity\User;
use App\Entity\Photo;
use App\Form\CommentType;
use App\Form\NewPhotoType;
// use Symfony\Component\Form\Extension\HttpFoundation\HttpFoundationRequest;
use App\Repository\PhotoRepository;
use Doctrine\ORM\EntityManagerInterface;
use Symfony\Component\HttpFoundation\Response;
use Symfony\Component\Routing\Annotation\Route;
use Symfony\Bundle\FrameworkBundle\Controller\AbstractController;
use Symfony\Component\HttpFoundation\Request as HttpFoundationRequest;

class PhotoController extends AbstractController
{
    #[Route('/', name: 'photo.list')]
    public function list(PhotoRepository $photoRepository): Response
    {
        // $photos = new Photo();
        // $photo->setTitle('Ma première photo');
        // $photo->setPostAt( new \DateTimeImmutable()); 
        // $photos = [];
        // $photos[] = $photo;
        $photos = $photoRepository->findAll();
        return $this->render('photo/list.html.twig', ['photos' => $photos]);


        // return $this->render('photo/index.html.twig', [
        //     'controller_name' => 'PhotoController',
        // ]);
    }
    #[Route('/photo/show/{id}', name: 'photo.show')]
    public function show(Photo $photo, EntityManagerInterface $em, HttpFoundationRequest $request)
    {
        if ($this->getUser()) {
            $user = $this->getUser();

            $comment = new \App\Entity\Comment();
            $comment->setUser($user);
            $comment->setPhoto($photo);
            $comment->setCreateAt(new \DateTimeImmutable());

            $form = $this->createForm(CommentType::class, $comment);
            $form->handleRequest($request);
            if($form->isSubmitted()&& $form->isValid()) {
                $em->persist($comment);
                $em->flush();

                return $this->redirectToRoute('photo.show',['id' => $photo->getId()]);
            }else {
                return $this->render('photo/show.html.twig', [
                    'photo' => $photo,
                    'form' => $form->createView(),
                ]);
            } 

        } else {
            return $this->render('photo/show.html.twig',[
                'photo'=>$photo,
            ]);
        }
    }

    #[Route('/photo/manage', name: 'photo.manage')]
    public function manage()
    {
        $user = $this->getUser();
        $photos = $user->getPhotos();
        return $this->render('photo/manage.html.twig', ['photos' => $photos]);
    }

    #[Route('/photo/delete/{id}', name: 'photo.delete')]
    public function delete(PhotoRepository $repository, HttpFoundationRequest $request, EntityManagerInterface $manager)
    {
        $photo = $repository->find($request->get('id'));

        // $manager = $this->getDoctrine()->getManager();  
        $manager->remove($photo);
        $manager->flush();
        return $this->redirectToRoute('photo.manage');
    }
    
    #[Route('/photo/delete/{id}', name: 'photo.delete')]
    public function deleteComment(PhotoRepository $repository, HttpFoundationRequest $request, EntityManagerInterface $manager)
    {
        $photo = $repository->find($request->get('id'));

        // $manager = $this->getDoctrine()->getManager();  
        $manager->remove($photo);
        $manager->flush();
        return $this->redirectToRoute('photo.manage');
    }
    #[Route('/photo/new', name: 'photo.new')]
    public function new(HttpFoundationRequest $request, EntityManagerInterface $manager)
    {
        $photo = new Photo();
        $form = $this->createForm(NewPhotoType::class, $photo);
        $form->handleRequest($request);
        if ($form->isSubmitted() && $form->isValid()) {

            $photo->setUser($this->getUser());
            $photo->setPostAt(new \DateTimeImmutable());
            $manager->persist($photo);
            $manager->flush();
            return $this->redirectToRoute('photo.list');
        }
        return $this->render('photo/new.html.twig', [
            'form' => $form->createView()
        ]);
    }
}

templates/photo/list.html.twig
{% extends 'base.html.twig' %}


{% block body %}
	<style>
		.example-wrapper {
			margin: 1em auto;
			max-width: 800px;
			width: 95%;
			font: 18px / 1.5 sans-serif;
		}
		.example-wrapper code {
			background: #F5F5F5;
			padding: 2px 6px;
		}
	</style>

	<div class="example-wrapper">
	

		
		<div class="container">
			<h2>Les photos</h2>
			<div class="row flex">
				{% for photo in photos %}
					<div class="col-3">
						<div class="card">
							<img class="card-img-top" src="{{ vich_uploader_asset(photo, 'imageFile') }}" alt="photo de {{ photo.user.pseudo}}">
							<div class="card-boby">
								<h5 class="card-title">
									<a href="{{ path('photo.show', {id: photo.id}) }}">{{ photo.title }}</a>
								</h5>
								<h5>Postée par : {{photo.user.pseudo}}</h5>
								<p class="card-text">Postée le :
									{{ photo.postAt }}</p>
								<div class="text-primary" style="font-weight: bold; font-size: 1.2rem;">commentaires : {{photo.comments|length}}</div>
							</div>
						</div>
					</div>
				{% endfor %}
			</div>
		</div>

	</div>
{% endblock %}

templates/photo/manage.html.twig
{% extends 'base.html.twig' %}

{% block body %}
	<div class="container">
		<h2>Liste de vos photos</h2>
		<div class="row flex">
			{% for photo in photos %}
				<div class="col-8">
					<table class="table table-striped">
						<tr>
							<th>Titre</th>
							<th>Date</th>
							<th>Nombre de commentaire</th>
							<th></th>
						</tr>
						<tr>
							<td>{{ photo.title }}</td>
							<td>{{ photo.postAt }}</td>
							<td>{{photo.comments|length}}</td>
							<td>
								<a href="{{ path("photo.delete", {id: photo.id}) }}" class="btn btn-secondary">
									Supprimer</a>
							</td>
						</tr>
					</table>
				</div>
			{% endfor %}
			<div class="col-4">
				
				<a href="{{ path("photo.new") }}" class="btn btn-primary">Ajouter une photo</a>
			</div>
		</div>
	</div>
{% endblock %}

templates/photo/new.html.twig
{% extends "base.html.twig" %}
{% block title 'Uploader une photo' %}
{% block body %}
	<div class="container mt-4">
		{{ form_start(form) }}
		<div class="row">
			<div class="col-md-4">{{  form_row(form.title) }}</div>
		</div>
		<div class="row">
			<div class="col-md-2">{{  form_row(form.imageFile) }}</div>
		</div>
		<button class="btn btn-primary">Poster</button>
		{{ form_end(form) }}
	</div>
{% endblock %}

templates/photo/show.html.twig
{% extends 'base.html.twig' %}

{% block body %}
	<div class="jumbotron">
		<div class="container">
			<div class="row">
				<div class="col-md-8">
					<img src="{{ vich_uploader_asset(photo, 'imageFile') }}" alt="photo de {{ photo.user.pseudo}}" style="width: 100%; height: auto;">
				</div>
				<div class="col-md-4">
					<h1>{{photo.title }}</h1>
					<h2>Postée le :
						{{ photo.postAt|date("d/m/Y") }}</h2>
					<div class="text-primary" style="font-weight: bold; font-size: 1.3rem">
						<p>Par :
							{{ photo.user.pseudo }}</p>
					</div>
					{% if app.user %}
						
						<div id="commentForm" class="mt-4">
							{{ form_start(form) }}
							<div class="row">
								<div class="col">{{ form_row(form.content) }}</div>
							</div>
							<div class="form-group">
								<button class="btn btn-primary">Envoyer</button>
							</div>
							{{ form_end(form) }}
						</div>
					{% endif %}
				</div>
			</div>
		</div>
	</div>
	<div class="container mt-4">
		<div class="row">
			<div class="col-md-8">
				<h2>Commentaires</h2>
				<table class="table table-striped">
					<tr>
						<th>Commentée par</th>
						<th>Date</th>
						<th>Commentaire</th>
					</tr>
					{% for comment in photo.comments %}

						<tr>
							<td>{{ comment.user.pseudo }}</td>
							<td>{{ comment.createAt|date("d/m/Y") }}</td>
							<td>{{ comment.content }}</td>
						</tr>
					{% endfor %}
				</table>
			</div>
		</div>
	{% endblock %}